spring.application.name=UserService

server.port = 8081
spring.datasource.url=jdbc:postgresql://localhost:2407/mydb
spring.datasource.username = postgres
spring.datasource.password = 12345
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql = true
spring.jpa.hibernate.ddl-auto = update

# Eureka Server URL
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

# Network/Registration Preferences
eureka.instance.prefer-ip-address=true
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true